/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public int add(int a,int b) {
        int c=0;
        c=a+b;

        return c;
    }
}
